.TH tempread 8
.SH NAME
tempread \- read temprature and monitor its changes
.SH SYNOPSIS
.B tempread
[\fB\-d\fR]
[\fIdevice number\fR]
.SH DESCRIPTION
.B tempread
read the current temprature based on user option
.SH OPTIONS
.TP
.BR \-d     
\fIserial number\fR
.TP
allow user specify the device serial number
.TP
.BR \-v
verbose mode
.TP
.BR non
display the default device message 
